### ISSUE TITLE
Add "Do you need assistance" banner if not activated

### ISSUE THREAD

**Issue by iverok** [vippsas/vipps-login-wordpress#20]
`Hei Iver, her er forslag til tekst for oppfølging (samme banner og logo): Til deg som har lastet ned Vipps logg inn plugin: Det er raskt og enkelt å komme i gang! Hent API nøkler i Vipps portalen og legg de inn i plugin for å aktivere Vipps Logg Inn. Se her!”`

Vis, dismissable, for kunder som har lastet ned men ikke aktivert.

**Comment by cloveras** [comment]
«Legg dem inn» (ikke «de»). 😉

**Comment by cloveras** [comment]
Også tror jeg markedsavdelingen liker «VippsPortalen».

**Comment by iverok** [comment]
Fikset lenke og laget dismissable banner som dukker opp om pluginen ikke blir konfigurert etter tre dager.
