### ISSUE TITLE
Login with vipps phone question

### ISSUE THREAD

**Issue by pdewouters** [vippsas/vipps-login-wordpress#26]
I've implemented a customisation to find a user account by their vipps phone number, but it was reported to me that one user's account got linked to the wrong vipps account, it showed someone elses phone number in their profile

this is the code https://gist.github.com/pdewouters/c500d010b2753a8b37a7a62a0b95ea9d

Do you see anything in there that could cause this? 

Unless it's due to multisite / redis cache mixing up the DB options? this happens with another plugin that was network active

**Comment by cloveras** [comment]
Is this code part of the official "Log in with Vipps for WordPress and WooCommerce" plugin (in this repo)? https://vippsas.github.io/vipps-developer-docs/docs/vipps-plugins/

If so: @iverok knows this in detail.

This FAQ may be relevant: https://vippsas.github.io/vipps-developer-docs/docs/vipps-developers/faqs/users-and-payments-faq#is-there-an-api-for-retrieving-information-about-a-vipps-user

**Comment by pdewouters** [comment]
@cloveras no it's custom code that hooks into the plugin

**Comment by iverok** [comment]
I'm sorry, I haven't had the time to look at this today. 

You should not get another users' phone number of course, but be aware that unless you have constrained  your Phone field in the user_meta table to be unique, you may have several users with the same number.  In that case you will find one of them nondeterministically.  I would also just to be sure disable that method for admins and so forth, just to be sure - ie, require those to use verified email addresses.

Other than that, the code  doesn't seem wrong;  you should be able to return any user from that hook using the Vipps info.  You may try to delete the user record from the PREFIX_vipps_login_users table and have the user try again, with extra logging in place.

(And sanitizing the phone number.. vipps will at some point support other countries than +47 and then you may get hash conflict so to speak.)
