### ISSUE TITLE
Test mode

### ISSUE THREAD

**Issue by kimmenbert** [vippsas/vipps-login-wordpress#40]
Hi! Would be great if you introduced test mode in the plugin, so we could use test / dev credentials

**Comment by iverok** [comment]
You actually can, just not using the Settings page. We're trying to limit this page to as few settings as possible.

It is possible to use these filters:

```php
'login_with_vipps_test_clientid'
'login_with_vipps_test_clientsecret'
'login_with_vipps_test_mode'
``` 

All of these take one argument and returns the test client id, the test client secret and then a boolean to indicate if the test mode should be turned on.
